### ISSUE TITLE
CPU usage at idle

### ISSUE THREAD

**Issue by raqbit** [mrbenshef/Boop-GTK#102]
When I launch Boop-GTK (v1.1.0) via `flatpak run uk.co.mrbenshef.Boop-GTK` or via the Gnome overview, it starts using ~40% of my CPU (Intel Core i5-7200U, Quad Core) while the application is not being used.

![image](https://user-images.githubusercontent.com/11144180/92302568-96480f00-ef6d-11ea-9a3e-c414dabcaf3e.png)

I'm not sure what's going on here, but I'm pretty sure this shouldn't be the case. Boop-GTK does not output any major errors in its log as far as I can see, just the following lines:
```
Gtk-Message: 11:44:39.158: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:44:39.158: Failed to load module "canberra-gtk-module"

(boop-gtk:2): GLib-GObject-CRITICAL **: 11:44:49.354: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(boop-gtk:2): GLib-GObject-CRITICAL **: 11:44:50.890: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(boop-gtk:2): GLib-GObject-CRITICAL **: 11:44:51.076: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(boop-gtk:2): GLib-GObject-CRITICAL **: 11:44:51.089: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(boop-gtk:2): GLib-GObject-CRITICAL **: 11:44:51.169: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by zoeyfyi** [comment]
Thanks for the report! Fixed in #103.
