### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [mrbenshef/Boop-GTK#108]
I think this app could benefit from a better icon that follows the [HIG](https://developer.gnome.org/hig/stable/icon-design.html.en) more closely.

I took a quick stab at redrawing it in that style:

![image](https://user-images.githubusercontent.com/1908896/92331191-23c25680-f075-11ea-9098-00e00b8c080b.png)

**Comment by zoeyfyi** [comment]
That looks great! Did you want to send a pull request? Alternatively if you can share the source file I can make the change.

Instead of ">", prehaps the [metamorphosis](resources/icons/scalable/actions/boop-gtk-metamorphose-symbolic.svg) icon is more symbolic of what the applications purpose is, to transform text. What do you think?

**Comment by bertob** [comment]
That sounds interesting, I'll give it a try! By the way, would you be open to having some more unique colors here, or do you want to keep the gray to stay closer to Boop for Mac?

**Comment by zoeyfyi** [comment]
I think it's fine to deviate in this regard. Excited to see what you come up with!

**Comment by bertob** [comment]
I was wondering if we could just make the metamorphosis symbol the entire icon:

![image](https://user-images.githubusercontent.com/1908896/93030021-1b8f8b80-f620-11ea-86b7-2150f26e1f61.png)

Otherwise, something more traditional is definitely also an option:

![image](https://user-images.githubusercontent.com/1908896/93030036-37932d00-f620-11ea-8a9b-e21b5ab10854.png)

**Comment by zoeyfyi** [comment]
They both look great! I do really like the top one though, it's more unique and the colours are great.

**Comment by bertob** [comment]
Iterated a bit on the first one, I like that the colors are more continuous here:

![image](https://user-images.githubusercontent.com/1908896/93463241-c7b6c800-f8e7-11ea-8836-888196e5d88c.png)

If this looks good to you I can do an MR

**Comment by bertob** [comment]
So I'm not sure what exactly happened, but somehow we ended up with the wrong icon being merged? Did I include the wrong one it in my PR? Either way, you can just re-export it from the `.Source` SVG with App Icon Preview, that one has the correct icon.

By the way, I would not recommend renaming the `.Source` svg file "icon.svg", it's needed for App Icon Preview. Keeping the `org.app.id.Source.svg` format is going to save you headaches later on :)

**Comment by zoeyfyi** [comment]
> So I'm not sure what exactly happened, but somehow we ended up with the wrong icon being merged? Did I include the wrong one it in my PR? Either way, you can just re-export it from the .Source SVG with App Icon Preview, that one has the correct icon.

Good catch, should be resolved now.

> By the way, I would not recommend renaming the .Source svg file "icon.svg", it's needed for App Icon Preview. Keeping the org.app.id.Source.svg format is going to save you headaches later on :)

I see, good to know!

**Comment by bertob** [comment]
> Good catch, should be resolved now.

You sure? I just pulled trunk, and the icons still look like this:

![image](https://user-images.githubusercontent.com/1908896/93584454-9dc3db00-f9a5-11ea-8477-197054a04f76.png)

![image](https://user-images.githubusercontent.com/1908896/93584546-bcc26d00-f9a5-11ea-9d5b-b12adc639d87.png)

**Comment by zoeyfyi** [comment]
On the `release-1.2.0` branch

**Comment by bertob** [comment]
Aha, gotcha :)

I suppose this issue can be closed then?

**Comment by zoeyfyi** [comment]
Released in [1.2.0](https://github.com/mrbenshef/Boop-GTK/releases/tag/v1.2.0)
