### ISSUE TITLE
Descriptions aren't searched, only titles

### ISSUE THREAD

**Issue by qcasey** [mrbenshef/Boop-GTK#130]
Searching for "color" doesn't bring up the Hex to RGB tool, even though "color" is in the description.

Similarly, "escape", "lower", "length", "whitespace", are all keywords that only appear in descriptions, making search come up empty.

This might be more of an issue once more tools are added, but it's a QoL thing that would be super helpful. Great app by the way, I use it more every day. 😊

**Comment by zoeyfyi** [comment]
Yes, this was definitely on my todo list. Unfortunately, last time I checked, there wasn't a simple fuzzy search crate that could search across multiple fields. I will take another look though. 

> Great app by the way, I use it more every day. 😊

Thanks, that's great to hear!
