### ISSUE TITLE
Change status bar messages to in-app notifications

### ISSUE THREAD

**Issue by TiZ-HugLife** [mrbenshef/Boop-GTK#134]
So there's this blank, useless chunk of space at the bottom of the window, a thick status bar of some sort? What exactly is the point of it? It appears to not be an issue with my theme or CSS customizations because it appears in both screenshots here, but the original Boop doesn't show a status bar on its screenshot. Any reason to keep that thing around?

**Comment by zoeyfyi** [comment]
It's to display errors and messages. For example if you run the line count action the result will display there. Boop uses the button thing (not sure what it's called on MacOS) at the top to display this information. Initially I did the same, but GTK's buttons aren't suited to display lots of information like that.

Perhaps in-app notifications would be a better for this, but they would appear on top of the editor which could be annoying.

**Comment by TiZ-HugLife** [comment]
Ahhh okay. Does it need to be so thick, and does it need to be there all the time?

**Comment by zoeyfyi** [comment]
Well the size depends on your gtk theme, its just a standard component. Having thought about this a bit more, I do think in-app notifications make more sense for info/errors then the status bar can be removed.
