### ISSUE TITLE
Request: Ctrl-Q to Quit

### ISSUE THREAD

**Issue by KSXGitHub** [mrbenshef/Boop-GTK#154]

**Comment by zoeyfyi** [comment]
Is Ctrl+Q really that universal? What's wrong with Alt+F4?

You can also define a shortcut to quit a GTK application in your GTK theme, something like [this](https://jnrowe.github.io/articles/tips/Custom_locations_in_the_GTK_filechooser.html).

**Comment by KSXGitHub** [comment]
> Is Ctrl+Q really that universal?

It is a common occurrence in the apps I use:
- Visual Studio Code
- Sublime Text
- Text Editor (gedit)
- System Monitor (gnome-system-monitor)
- Usage (gnome-usage)
- Files (nautilus)
- Micro Editor
- etc.

Some terminal apps also have Ctrl-Q or Q.

> What's wrong with Alt+F4?

Compared to Ctrl-Q, it is harder to press.

Every one of my uses for Boop-GTK is very brief (mostly sorting lines), so I expect a faster exit.
