### ISSUE TITLE
Request: Also load custom scripts from $XDG_CONFIG_DIRS/boop-gtk/scripts

### ISSUE THREAD

**Issue by KSXGitHub** [mrbenshef/Boop-GTK#158]
## Problem

I want to distribute some custom boop scripts with distribution package manager (e.g. pacman). I know that Boop-GTK loads custom scripts from `$XDG_CONFIG_HOME/boop-gtk/scripts` but that path is inside `$HOME`, so I can't install custom scripts there.

## Proposal

Also load custom scripts from system paths independent of user, such as `/etc/xdg/boop-gtk/scripts` (`$XDG_CONFIG_DIRS` is a list of directory paths separated by `:` and `/etc/xdg` is the default value on Arch Linux).

**Comment by zoeyfyi** [comment]
Great idea! I'll look into this.
