### ISSUE TITLE
Dropping Windows support

### ISSUE THREAD

**Issue by zoeyfyi** [mrbenshef/Boop-GTK#193]
- The majority of my time is spent fixing problems with the windows build
- Since this project requires gvsbuild (building V8 on MSYS is... [difficult](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-v8)) upgrading to gtk4 is blocked if/when gvsbuild provides it
- The windows build takes 30+ minuets
- The last release had 27 downloads
- [Woop](https://github.com/felixse/Woop) is a native windows port of Boop, doesn't have a release but its probably the superior way to do a Windows version

**Comment by felixse** [comment]
Ok, I better hurry up 😄
