### ISSUE TITLE
Redo last action button

### ISSUE THREAD

**Issue by GHNewbiee** [mrbenshef/Boop-GTK#229]
What about adding a "Redo" button which will apply the last script run. *Tia*

**Comment by zoeyfyi** [comment]
This has been discussed upstream, I think my preferred solution to this is to order the scripts in the command palette by most recently used, then applying the same script again is `Ctrl+Shift+P` and `Enter`. Perhaps even a redo shortcut as well.

**Comment by GHNewbiee** [comment]
> This has been discussed upstream, I think my preferred solution to this is to order the scripts in the command palette by most recently used,

Good idea as an extra feature.

> then applying the same script again is `Ctrl+Shift+P` and `Enter`.

Waste of energy! I remove the right hand from mice, I set both hands to the keyboard, etc..., instead of two clicks! *Real admins do it by hands on keyboard, intelligent users do it by mice in hand!*

> Perhaps even a redo shortcut as well.
IMHO, this is the fastest way!

**Comment by felixse** [comment]
The macOS version has "Re-execute Last Script" mapped to CMD+Shift+B
