### ISSUE TITLE
Buffer doesn't gain focus after script execution

### ISSUE THREAD

**Issue by GHNewbiee** [mrbenshef/Boop-GTK#230]
I have observed that after running "Minify CSS" script, the result is not focused automatically. I have to click in the text in order to do "Ctrl+A" which is waste of time and energy. Moving the mice and clicking consumes energy... In addition, the result, most of the times, will need to be copied and pasted. *Tia*

**Comment by zoeyfyi** [comment]
Hmm, can't seem to reproduce this on my end. Which platform and format are you on (e.g. linux binary, flatpak, snap)?

**Comment by GHNewbiee** [comment]
I use LinuxMint 20.1 and Linux binary. If you get different result, then just keep it in mind.

**Comment by zoeyfyi** [comment]
I created a linux mint VM and was still unable to replicate the issue. Perhaps the issue is an old version of gtksourceview?

**Comment by GHNewbiee** [comment]
Maybe, I do not really know. As I said, just keep it in your mind. If other people complain, too, in future then you investigate it again. If you wish, you can close it.

**Comment by zoeyfyi** [comment]
You could try `apt install libgtksourceview-3.0-1` to see if you have an old version. Otherwise I am not sure what else I can do to try and replicate this :/

**Comment by GHNewbiee** [comment]
It is already installed. See next photo.

![boop](https://user-images.githubusercontent.com/26875662/107885698-1ea6e480-6efc-11eb-91d6-eb87db10f22d.png)

> ... Otherwise I am not sure what else I can do to try and replicate this :/

In the IT world there are many inconsistencies, imperfections and weird things happen sometimes. Don't waste your time. One time after update many menu entries disappeared for 1 month. I run most of the apps from console. One day they appeared back again.

**Comment by zoeyfyi** [comment]
Hold on, I think I found the issue! When clicking the button, focus is returned to the button when the command palette closes. I always use the keyboard shortcut which keeps the sourceview focused. Can you confirm that its only when using the mouse to open the command palette that the sourceview doesn't gain focus?

**Comment by GHNewbiee** [comment]
> Can you confirm that its only when using the mouse to open the command palette that the sourceview doesn't gain focus?

Yes, I can and I do confirm that.
