### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by mrbenshef** [mrbenshef/Boop-GTK#4]
Currently the build fails on windows:

```
LINK : fatal error LNK1181: cannot open input file 'gtksourceview-3.0.lib'
```

This happens despite installing the `gtksourceview` package with:

```
pacman -S --noconfirm mingw-w64-x86_64-gtk3 mingw-w64-x86_64-gtksourceview3 mingw-w64-x86_64-gtksourceviewmm3
```

My guess is that `mingw-w64-x86_64-gtksourceview3` install the lib with a different name, but I can't debug this until I set up a windows machine.

**Comment by zoeyfyi** [comment]
Resolved in v0.1.0
