### ISSUE TITLE
`extern crate` isn't necessary after Rust 2018

### ISSUE THREAD

**Issue by marioortizmanero** [mrbenshef/Boop-GTK#74]
Just wanted to let you know that the `extern crate` statements found in `main.rs` - for example - aren't really necessary when using Rust 2018. Removing them will clean up your code a bit.

**Comment by zoeyfyi** [comment]
Thanks!

**Comment by marioortizmanero** [comment]
For what I've seen, you've replaced the `extern crate XYZ` with `use XYZ`. But that is not necessary either. And you left the `extern crate` with `#[cfg(...)]` in the previous line, which aren't necessary either because `Cargo.toml` already makes sure the `cfg` is followed.

**Comment by zoeyfyi** [comment]
Ah, thanks once again @marioortizmanero! I should really know better since I submitted a patch to another repo with the exact same problem :sweat_smile:
