### ISSUE TITLE
Use primary menu icon

### ISSUE THREAD

**Issue by bertob** [mrbenshef/Boop-GTK#82]
The primary menu uses a color settings icon, which looks odd. The HIG recommends `menu-open-symbolic` for this: https://developer.gnome.org/hig/stable/primary-menus.html.en

![image](https://user-images.githubusercontent.com/1908896/90319692-b2dac380-df3a-11ea-812c-9ee43b7d3e3e.png)

**Comment by zoeyfyi** [comment]
I agree that it looks odd, especially with the Adwaita theme. I don't have `menu-open-symbolic` on my system, is it standard? There is also `open-menu-symbolic` which is similar.

**Comment by bertob** [comment]
My bad, it's actually `open-menu-symbolic` :)
